server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.0.109

aliyun:
  sms:
    accessKeyId: LTAIpGYhPa6tmvUO
    accessKeySecret: tTUTTAqzIZx0xfaICzSzZzoKZT1dM0
    template_code: SMS_158440564
    sign_name: 金鑫自己测试学习用的签名

